import {
    HiChartPie,
    HiUser,
    HiCollection,
    HiAdjustments,
    HiPlusCircle,
    HiCurrencyDollar,
    HiCash,
    HiClipboardList,
    HiHashtag,
    HiUsers,
    HiUserGroup,
    HiUserCircle,
    HiOutlineTruck,
    HiDatabase,
    HiShoppingBag,
    HiReceiptTax,
    HiHome,
    HiInboxIn,
    HiOutlineCash,
    HiOutlineTable,
    HiOutlineCog,
    HiDocument
} from "react-icons/hi";

export default [
    {
        name: "Dashboard",
        show: true,
        icon: HiChartPie,
        route: route("dashboard"),
        active: "dashboard",
        permission: "view-dashboard",
    },
    {
        name: "Kain",
        show: true,
        icon: HiDocument,
        route: route("fabric.index"),
        active: "fabric.*",
        permission: "view-fabric",
    },
    {
        name: "Artikel",
        show: true,
        icon: HiClipboardList,
        route: route("production.index"),
        active: "production.*",
        permission: "view-production",
    },
    {
        name: "Line Sewing",
        show: true,
        icon: HiOutlineCog,
        route: route("line.sewing.index"),
        active: "line.sewing.index",
        permission: "create-production-result",
    },
    {
        name: "Master",
        show: true,
        icon: HiCollection,
        items: [
            {
                name: "Ukuran",
                show: true,
                icon: HiClipboardList,
                route: route("size.index"),
                active: "size.*",
                permission: "view-size",
            },
            {
                name: "Warna",
                show: true,
                icon: HiClipboardList,
                route: route("color.index"),
                active: "color.*",
                permission: "view-color",
            },
            {
                name: "Bahan",
                show: true,
                icon: HiClipboardList,
                route: route("material.index"),
                active: "material.*",
                permission: "view-material",
            },
            {
                name: "Brand",
                show: true,
                icon: HiClipboardList,
                route: route("brand.index"),
                active: "brand.*",
                permission: "view-brand",
            },
            {
                name: "Pembeli",
                show: true,
                icon: HiClipboardList,
                route: route("buyer.index"),
                active: "buyer.*",
                permission: "view-buyer",
            },
            {
                name: "Supplier",
                show: true,
                icon: HiClipboardList,
                route: route("supplier.index"),
                active: "supplier.*",
                permission: "view-supplier",
            },
            {
                name: "Ratio",
                show: true,
                icon: HiClipboardList,
                route: route("ratio.index"),
                active: "ratio.*",
                permission: "view-ratio",
            },
        ],
    },
    {
        name: "User",
        show: true,
        icon: HiUser,
        items: [
            {
                name: "Roles",
                show: true,
                icon: HiUserGroup,
                route: route("roles.index"),
                active: "roles.*",
                permission: "view-role",
            },
            {
                name: "Users",
                show: true,
                icon: HiUsers,
                route: route("user.index"),
                active: "user.index",
                permission: "view-user",
            },
        ],
    },
];
