import {
    HiChartPie,
    HiUser,
    HiCollection,
    HiAdjustments,
    HiPlusCircle,
    HiCurrencyDollar,
    HiCash,
    HiClipboardList,
    HiHashtag,
    HiUsers,
    HiUserGroup,
    HiUserCircle,
    HiOutlineTruck,
    HiDatabase,
    HiShoppingBag,
    HiReceiptTax,
    HiHome,
    HiInboxIn,
    HiOutlineCash,
    HiOutlineTable
} from "react-icons/hi";

export default [
    {
        name: "Dashboard",
        show: true,
        icon: HiChartPie,
        route: route("dashboard"),
        active: "dashboard",
        permission: "view-dashboard",
    },
    {
        name: "Master",
        show: true,
        icon: HiCollection,
        items: [
            {
                name: "Ukuran",
                show: true,
                icon: HiClipboardList,
                route: route("size.index"),
                active: "size.*",
                permission: "view-size",
            },
            {
                name: "Bahan",
                show: true,
                icon: HiClipboardList,
                route: route("material.index"),
                active: "material.*",
                permission: "view-material",
            },
            {
                name: "Brand",
                show: true,
                icon: HiClipboardList,
                route: route("brand.index"),
                active: "brand.*",
                permission: "view-brand",
            },
        ],
    },
    {
        name: "User",
        show: true,
        icon: HiUser,
        items: [
            {
                name: "Roles",
                show: true,
                icon: HiUserGroup,
                route: route("roles.index"),
                active: "roles.*",
                permission: "view-role",
            },
            {
                name: "Users",
                show: true,
                icon: HiUsers,
                route: route("user.index"),
                active: "user.index",
                permission: "view-user",
            },
        ],
    },
];
